Repository boostcampwm-2024/refactor-ios11-alsongDalsong, pull requests merged in 2025-02, with the labels that each got.

#35 [Refactor] 에러 핸들링 개선
  alsongDalsong/ASAudioKit/ASAudioAnalyzer.swift
  alsongDalsong/ASAudioKit/ASAudioErrors.swift
  alsongDalsong/ASAudioKit/ASAudioKit.xcodeproj/project.pbxproj
  alsongDalsong/ASAudioKit/ASAudioKit/ASAudioPlayer/ASAudioPlayer.swift
  alsongDalsong/ASAudioKit/ASAudioKit/ASAudioRecorder/ASAudioRecorder.swift
  alsongDalsong/ASDecoder/ASDecoder.xcodeproj/project.pbxproj
  alsongDalsong/ASDecoder/ASDecoder/ASDecoder.swift
  alsongDalsong/ASDecoder/ASDecoderErrors.swift
  alsongDalsong/ASEncoder/ASEncoder.xcodeproj/project.pbxproj
  alsongDalsong/ASEncoder/ASEncoder/ASEncoder.swift
  alsongDalsong/ASEncoder/ASEncoderErrors.swift
  alsongDalsong/ASMusicKit/ASMusicErrors.swift
  alsongDalsong/ASMusicKit/ASMusicKit.xcodeproj/project.pbxproj
  alsongDalsong/ASMusicKit/ASMusicKit/ASMusicAPI.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/ASNetworkErrors.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/ASNetworkManager.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseAuth.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseDatabase.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseStorage.swift
  alsongDalsong/ASRepository/ASRepository/ASRepositoryErrors.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/AnswersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/AvatarRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/DataDownloadRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RecordsRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomActionRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/SubmitsRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/ASErrors.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/AudioHelper.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/LogHandler.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Game/GameNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Loading/LoadingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
Labels: refactor

#40 [Feat] AI 데이터 수집을 위한 녹음 데모앱 생성
  alsongDalsong.xcworkspace/contents.xcworkspacedata
  alsongDalsong.xcworkspace/xcshareddata/swiftpm/Package.resolved
  alsongDalsong/ASAIKit/ASAIKit.xcodeproj/project.pbxproj
  alsongDalsong/ASAIKit/ASAIKit/ASAIKit.h
  alsongDalsong/ASAIKit/ASAIKitDemo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  alsongDalsong/ASAIKit/ASAIKitDemo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  alsongDalsong/ASAIKit/ASAIKitDemo/Resources/Assets.xcassets/Contents.json
  alsongDalsong/ASAIKit/ASAIKitDemo/Resources/Fonts/DoHyeon-Regular.ttf
  alsongDalsong/ASAIKit/ASAIKitDemo/Resources/Info.plist
  alsongDalsong/ASAIKit/ASAIKitDemo/Sources/ASAIKitButton.swift
  alsongDalsong/ASAIKit/ASAIKitDemo/Sources/ASAIKitDemoApp.swift
  alsongDalsong/ASAIKit/ASAIKitDemo/Sources/ASAIKitDemoView.swift
  alsongDalsong/ASAIKit/ASAIKitDemo/Sources/ASAIKitDemoViewModel.swift
  alsongDalsong/ASAIKit/ASAIKitDemo/Sources/ASAIKitMessage.swift
Labels: feature

#45 [Feat] 앱 설치 후 최초 1회 실행 시의 튜토리얼 시작 뷰
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Loading/LoadingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/TutorialGuideViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/TutorialNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/TutorialState.swift
Labels: feature

#49 [Feat] Tutorial Navigation 연결
  alsongDalsong/alsongDalsong/alsongDalsong/Localizable.xcstrings
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/Alert/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Loading/LoadingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/Entity/TutorialState.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/Guide/TutorialGuideViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/Humming/HummingTutorialViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/Humming/HummingTutorialViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/Result/HummingResultTutorialViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/Result/HummingResultTutorialViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/SelectMusic/SelectMusicTutorialViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Tutorial/TutorialNavigationController.swift
Labels: enhancement
